"""Command surface (§8). Transport-agnostic by construction (R13.8).

No command accepts a phase, a cycle number, or executor identity (R8.3).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from . import (
    adapters,
    config as config_mod,
    contract as contract_mod,
    gitutil,
    identity,
    render,
    snapshot,
)
from .adapters.base import FAILED, NOT_COLLECTED
from .advance import advance as do_advance
from .envelope import Envelope, NextAction, Verb, failure
from .ledger import Ledger, now
from .machine import CLOSED, SKIPPED, Engine

BLOCKER_KINDS = {
    "regression", "target_unfixable", "bad_red", "plan_defect", "tooling",
    "context_exhausted",
}


def _worktree() -> Path:
    return gitutil.worktree_root(Path.cwd())


def _context(require_run: bool = True):
    worktree = _worktree()
    cfg = config_mod.load(worktree)
    ledger = Ledger(gitutil.repo_identity(worktree))
    run = ledger.active_run(str(worktree))
    if require_run and run is None:
        raise SystemExit(
            failure("no active run in this worktree; `tdd run start --plan <path>`").emit()
        )
    return worktree, cfg, ledger, run


def _engine(worktree, cfg, ledger, run) -> Engine:
    return Engine(ledger, cfg, worktree, run)


# -- commands ------------------------------------------------------------


def cmd_init(args) -> Envelope:
    worktree = _worktree()
    path = worktree / config_mod.CONFIG_NAME
    if path.exists() and not args.force:
        return failure(f"{path} already exists; pass --force to overwrite")

    detected = []
    for child in sorted(p for p in worktree.iterdir() if p.is_dir()):
        if child.name.startswith(".") or child.name == "node_modules":
            continue
        if (child / "pyproject.toml").is_file():
            detected.append((child.name, "pytest", '["tests/"]'))
        elif (child / "vitest.config.ts").is_file() or (child / "package.json").is_file():
            detected.append(
                (child.name, "vitest", '["**/__tests__/**", "**/*.test.ts", "**/*.test.tsx"]')
            )

    lines = ["# Generated by `tdd init` — review before use (P5: roots are declared).", ""]
    for name, adapter, tests in detected:
        lines += [
            f"[project.{name}]",
            f'root       = "{name}"',
            f'adapter    = "{adapter}"',
            f"test_paths = {tests}",
            "lint       = []",
            "typecheck  = []",
            "",
        ]
    path.write_text("\n".join(lines))
    return Envelope(
        result={"written": str(path), "detected": [d[0] for d in detected]},
        next_action=NextAction(
            Verb.CONFIRM_CYCLE_APPLICABLE,
            "Review tdd.toml: confirm roots, add lint/typecheck commands and artifact edges.",
        ),
    )


LEGACY_ARTIFACTS = (".pytest_report.json", ".tdd-state.json")
SKIP_DIRS = {"node_modules", ".venv", "venv", "__pycache__", ".git"}


def _legacy_artifacts(worktree: Path) -> list[Path]:
    """Find stale artifacts in *this* worktree only.

    Nested worktrees under `.claude/worktrees/` are separate checkouts with their own
    in-flight work; scanning into them reports another branch's live files as this
    worktree's problem.
    """
    found: list[Path] = []

    def walk(directory: Path, depth: int = 0) -> None:
        if depth > 8:
            return
        try:
            entries = list(directory.iterdir())
        except OSError:
            return
        for entry in entries:
            if entry.is_dir():
                if entry.name in SKIP_DIRS:
                    continue
                # A nested checkout owns its own state.
                if (entry / ".git").exists():
                    continue
                walk(entry, depth + 1)
            elif entry.name in LEGACY_ARTIFACTS:
                found.append(entry)

    walk(worktree)
    return sorted(found)


def cmd_doctor(args) -> Envelope:
    worktree = _worktree()
    checks: list[dict] = []

    def check(name, ok, detail=""):
        checks.append({"check": name, "ok": bool(ok), "detail": detail})

    check("worktree resolvable", True, str(worktree))
    try:
        cfg = config_mod.load(worktree)
        check("tdd.toml valid", True, f"{len(cfg.projects)} projects")
    except config_mod.ConfigError as exc:
        check("tdd.toml valid", False, str(exc))
        return Envelope(ok=False, error="configuration invalid", result={"checks": checks})

    repo = gitutil.repo_identity(worktree)
    ledger = Ledger(repo)
    check("ledger reachable", True, str(ledger.path))
    check("ledger outside worktree", not str(ledger.path).startswith(str(worktree)), str(ledger.path))

    for name, project in cfg.projects.items():
        root = worktree / project.root
        check(f"{name}: root exists", root.is_dir(), str(root))
        check(f"{name}: adapter known", project.adapter in adapters.REGISTRY, project.adapter)
        check(f"{name}: test_paths declared", bool(project.test_paths))
        if project.adapter == "pytest":
            code, out, err = adapters.base.run_command(
                "uv run python -c 'import pytest_jsonreport'", root
            )
            check(f"{name}: pytest-json-report installed", code == 0, (err or "")[:200])

    for art in cfg.artifacts.values():
        check(f"artifact {art.name}: has check or regenerate", bool(art.check or art.regenerate))

    stale = _legacy_artifacts(worktree)
    check("no legacy state artifacts", not stale, ", ".join(str(s) for s in stale[:5]))
    check("worktree clean", not gitutil.is_dirty(worktree))

    ok = all(c["ok"] for c in checks)
    return Envelope(
        ok=True,
        result={"checks": checks, "healthy": ok},
        next_action=NextAction(
            Verb.CONFIRM_CYCLE_APPLICABLE if ok else Verb.RESOLVE_BLOCKER,
            "Environment is ready." if ok else "Resolve the failing checks above.",
        ),
    )


def cmd_plan_register(args) -> Envelope:
    worktree = _worktree()
    cfg = config_mod.load(worktree)
    ledger = Ledger(gitutil.repo_identity(worktree))
    rel = str(Path(args.plan))
    try:
        parsed = contract_mod.register(worktree, rel, cfg)
    except contract_mod.ContractError as exc:
        # R7.10 — malformed front-matter is a planning defect and must surface.
        return failure(f"malformed plan contract: {exc}", plan=rel)

    if parsed.status == "undeclared" and not args.allow_undeclared:
        return failure(
            f"{rel} has no front-matter contract. Add one, or pass --allow-undeclared"
            " (fidelity metrics will be unavailable).",
            plan=rel,
        )

    existing = ledger.one(
        "SELECT * FROM plan_contract WHERE plan_path = ? AND git_blob_sha IS ?",
        (rel, parsed.blob_sha),
    )
    contract_id = existing["id"] if existing else ledger.insert(
        "plan_contract",
        plan_path=rel,
        git_blob_sha=parsed.blob_sha,
        git_commit=parsed.commit_sha,
        status=parsed.status,
        declared_cycles=contract_mod.cycles_to_json(parsed.cycles),
        annotation_keys=json.dumps(parsed.annotation_keys),
        registered_at=now(),
    )
    return Envelope(
        result={
            "contract_id": contract_id,
            "status": parsed.status,
            "blob": parsed.blob_sha,
            "cycles": len(parsed.cycles),
            "kinds": {k: sum(1 for c in parsed.cycles if c.kind == k)
                      for k in {c.kind for c in parsed.cycles}},
            "reused": bool(existing),
        },
        next_action=NextAction(
            Verb.CONFIRM_CYCLE_APPLICABLE, f"Contract registered. `tdd run start --plan {rel}`."
        ),
    )


def cmd_run_start(args) -> Envelope:
    worktree = _worktree()
    cfg = config_mod.load(worktree)
    ledger = Ledger(gitutil.repo_identity(worktree))

    if ledger.active_run(str(worktree)) is not None:
        return failure("a run is already active in this worktree")

    rel = str(Path(args.plan))
    contract_row = ledger.one(
        "SELECT * FROM plan_contract WHERE plan_path = ? ORDER BY id DESC LIMIT 1", (rel,)
    )
    if contract_row is None:
        return failure(f"{rel} is not registered; run `tdd plan register {rel}` first")

    # R7.11 — the plan blob is the contract; drift must surface.
    blob_changed = False
    try:
        current_blob, _ = gitutil.blob_sha_at_head(worktree, rel)
        blob_changed = bool(
            contract_row["git_blob_sha"] and current_blob != contract_row["git_blob_sha"]
        )
    except gitutil.GitError:
        pass

    dirty = sorted(gitutil.dirty_paths(worktree))
    if dirty and not args.allow_dirty:
        return failure(
            "working tree is dirty; commit first or pass --allow-dirty"
            " (pre-existing changes are then excluded from authorship forever)",
            dirty=dirty,
        )

    if contract_row["status"] == "undeclared" and not args.allow_undeclared:
        return failure("contract is undeclared; pass --allow-undeclared")

    executor = identity.resolve(worktree, args.executor)
    run_id = ledger.insert(
        "run",
        plan_contract_id=contract_row["id"],
        executor_model=executor.model,
        executor_session=executor.session,
        executor_source=executor.source,
        worktree_path=str(worktree),
        started_at=now(),
        allow_dirty=int(bool(args.allow_dirty)),
        preexisting_dirty=json.dumps(dirty),
        config_sha=config_mod.config_sha(worktree),
    )
    run = ledger.one("SELECT * FROM run WHERE id = ?", (run_id,))
    if blob_changed:
        ledger.event(run_id, None, "plan_blob_changed", rel)

    # Baselines and the collection snapshot, per project (R9.5, R8.9).
    for name, project in cfg.projects.items():
        adapter = adapters.build(project, worktree)
        verdict = adapter.run(None)
        ledger.insert(
            "baseline", run_id=run_id, project=name,
            failing=json.dumps(sorted(verdict.failed)), captured_at=now(),
        )
        collection = adapter.collect()
        ledger.insert(
            "collection_snapshot", run_id=run_id, project=name,
            tests=json.dumps(sorted(collection.tests)),
            failed_files=json.dumps(collection.failed_files), captured_at=now(),
        )

    engine = Engine(ledger, cfg, worktree, run)
    engine.check_artifacts(None)
    first = engine.declared[0] if engine.declared else None
    if first is None:
        return failure("contract declares no cycles")
    cycle = engine.open_cycle(first.ordinal)

    verb, opening = engine.opening_action(cycle)
    detail = f"Run {run_id} started ({executor.model}, via {executor.source}). {opening}"
    return Envelope(
        run=engine.run_state(cycle),
        result={
            "baselines": {
                n: len(v) for n, v in ledger.baselines(run_id).items()
            },
            "executor_source": executor.source,
        },
        next_action=NextAction(verb, detail),
    )


def cmd_status(args) -> Envelope:
    worktree, cfg, ledger, run = _context(require_run=False)
    if run is None:
        return Envelope(
            result={"active": False},
            next_action=NextAction(
                Verb.CONFIRM_CYCLE_APPLICABLE, "No active run. `tdd run start --plan <path>`."
            ),
        )
    engine = _engine(worktree, cfg, ledger, run)
    cycle = ledger.open_cycle(run["id"])
    if cycle is None:
        return Envelope(
            run={"id": run["id"], "phase": CLOSED},
            next_action=NextAction(Verb.COMPLETE, "Run complete."),
        )
    attempts = len(ledger.invocations(cycle["id"], cycle["phase"]))
    return Envelope(
        run=engine.run_state(cycle),
        result={
            "attempts_in_phase": attempts,
            "targets": json.loads(cycle["target_tests"]),
            "sensitivity_open": ledger.open_sensitivity(cycle["id"]) is not None,
        },
        next_action=NextAction(
            Verb.REFACTOR_OR_ADVANCE, "Run `tdd advance` to evaluate the current phase."
        ),
    )


def cmd_advance(args) -> Envelope:
    worktree, cfg, ledger, run = _context()
    engine = _engine(worktree, cfg, ledger, run)
    cycle = ledger.open_cycle(run["id"])
    if cycle is None:
        return Envelope(
            run={"id": run["id"], "phase": CLOSED},
            next_action=NextAction(Verb.COMPLETE, "All cycles complete."),
        )
    return do_advance(engine, cycle, retry=args.retry)


def cmd_cycle_skip(args) -> Envelope:
    worktree, cfg, ledger, run = _context()
    engine = _engine(worktree, cfg, ledger, run)
    cycle = ledger.open_cycle(run["id"])
    if cycle is None:
        return failure("no open cycle")
    ledger.update(
        "cycle", cycle["id"], phase=SKIPPED, closed_at=now(), skip_reason=args.reason
    )
    ledger.insert(
        "transition", cycle_id=cycle["id"], from_phase=cycle["phase"],
        to_phase=SKIPPED, at=now(),
    )
    nxt_declared = next(
        (c for c in engine.declared if c.ordinal > cycle["ordinal"]), None
    )
    if nxt_declared is None:
        ledger.update("run", run["id"], ended_at=now(), outcome="complete")
        return Envelope(
            run={"id": run["id"], "cycle": cycle["ordinal"], "phase": SKIPPED},
            next_action=NextAction(Verb.COMPLETE, "Final cycle skipped; run complete."),
        )
    nxt = engine.open_cycle(nxt_declared.ordinal)
    verb, opening = engine.opening_action(nxt)
    return Envelope(
        run=engine.run_state(nxt),
        result={"skipped": cycle["ordinal"], "reason": args.reason},
        next_action=NextAction(
            verb, f"Cycle {cycle['ordinal']} skipped. {opening}"
        ),
    )


def cmd_annotate(args) -> Envelope:
    worktree, cfg, ledger, run = _context()
    cycle = ledger.open_cycle(run["id"])
    ledger.insert(
        "annotation", run_id=run["id"], cycle_id=cycle["id"] if cycle else None,
        key=args.key, value=args.value, at=now(),
    )
    return Envelope(
        run={"id": run["id"], "cycle": cycle["ordinal"] if cycle else None},
        result={"key": args.key},
        next_action=NextAction(Verb.REFACTOR_OR_ADVANCE, "Annotation recorded. `tdd advance`."),
    )


def cmd_blocker(args) -> Envelope:
    worktree, cfg, ledger, run = _context()
    if args.kind not in BLOCKER_KINDS:
        return failure(f"unknown blocker kind {args.kind!r}; use one of {sorted(BLOCKER_KINDS)}")
    cycle = ledger.open_cycle(run["id"])
    ledger.insert(
        "blocker", run_id=run["id"], cycle_id=cycle["id"] if cycle else None,
        kind=args.kind, detail=args.detail, at=now(),
    )
    # R8.7 — a blocked run is not live, so the stop hook must release.
    ledger.update("run", run["id"], ended_at=now(), outcome="blocked")
    return Envelope(
        run={"id": run["id"], "cycle": cycle["ordinal"] if cycle else None, "phase": "BLOCKED"},
        result={"kind": args.kind, "detail": args.detail},
        next_action=NextAction(
            Verb.BLOCKED,
            f"Run blocked ({args.kind}). A human can resume with"
            " `tdd resume --unblock --note ...`.",
        ),
    )


def cmd_resume(args) -> Envelope:
    worktree = _worktree()
    cfg = config_mod.load(worktree)
    ledger = Ledger(gitutil.repo_identity(worktree))
    run = ledger.active_run(str(worktree))

    if args.unblock:
        if run is not None:
            return failure("run is already live; --unblock applies to a blocked run")
        blocked = ledger.one(
            "SELECT * FROM run WHERE worktree_path = ? AND outcome = 'blocked'"
            " ORDER BY id DESC LIMIT 1",
            (str(worktree),),
        )
        if blocked is None:
            return failure("no blocked run to unblock in this worktree")
        if not args.note:
            return failure("--unblock requires --note describing the intervention")
        ledger.update("run", blocked["id"], ended_at=None, outcome=None)
        ledger.insert(
            "human_intervention", run_id=blocked["id"], note=args.note, at=now()
        )
        run = ledger.one("SELECT * FROM run WHERE id = ?", (blocked["id"],))

    if run is None:
        return failure("no active run in this worktree")

    engine = _engine(worktree, cfg, ledger, run)
    cycle = ledger.open_cycle(run["id"])
    if cycle is None:
        return Envelope(
            run={"id": run["id"], "phase": CLOSED},
            next_action=NextAction(Verb.COMPLETE, "Run complete."),
        )
    return Envelope(
        run=engine.run_state(cycle),
        result={"resumed": True},
        next_action=NextAction(
            Verb.REFACTOR_OR_ADVANCE,
            f"Resumed at cycle {cycle['ordinal']}, phase {cycle['phase']}. Run `tdd advance`.",
        ),
    )


def cmd_sensitivity(args) -> Envelope:
    worktree, cfg, ledger, run = _context()
    cycle = ledger.open_cycle(run["id"])
    if cycle is None:
        return failure("no open cycle")

    if args.step == "begin":
        if ledger.open_sensitivity(cycle["id"]) is not None:
            return failure("a sensitivity check is already open")
        check_id = ledger.insert(
            "sensitivity_check",
            cycle_id=cycle["id"],
            reference_diff=snapshot.capture(worktree, cfg),
            reference_untracked=snapshot.fingerprint(worktree, cfg),
            opened_at=now(),
        )
        return Envelope(
            run={"id": run["id"], "cycle": cycle["ordinal"]},
            result={"check_id": check_id},
            next_action=NextAction(
                Verb.RUN_SENSITIVITY_CHECK,
                "Reference state recorded. Mutate the behaviour under test, then"
                " `tdd sensitivity check`.",
            ),
        )

    open_check = ledger.open_sensitivity(cycle["id"])
    if open_check is None:
        return failure("no open sensitivity check; run `tdd sensitivity begin` first")
    engine = _engine(worktree, cfg, ledger, run)
    targets = json.loads(cycle["target_tests"])
    projects = json.loads(cycle["projects"])

    if args.step == "check":
        outcomes, _, _, failure_text = engine.run_projects(
            projects, targets, cycle, "SENSITIVITY", False
        )
        # A mutation that breaks collection also proves the test depends on the code.
        bites = bool(outcomes) and all(
            o in (FAILED, NOT_COLLECTED) for o in outcomes.values()
        )
        ledger.update(
            "sensitivity_check", open_check["id"],
            mutation_diff=gitutil.diff_text(worktree)[:20000],
            observed_failure=failure_text[:4000],
        )
        if not bites:
            return Envelope(
                ok=False,
                error="the mutation did not make the target fail — the test pins nothing",
                run={"id": run["id"], "cycle": cycle["ordinal"]},
                result={"outcomes": outcomes},
                next_action=NextAction(
                    Verb.RUN_SENSITIVITY_CHECK,
                    "Strengthen the mutation or the assertion, then check again.",
                ),
            )
        return Envelope(
            run={"id": run["id"], "cycle": cycle["ordinal"]},
            result={"outcomes": outcomes, "observed_failure": failure_text[:800]},
            next_action=NextAction(
                Verb.RUN_SENSITIVITY_CHECK,
                "The test fails under mutation. Restore with `tdd sensitivity end`.",
            ),
        )

    # end — restore and verify byte-identical (R8.5)
    to_restore = snapshot.restore(worktree, cfg, open_check["reference_diff"])
    restored_ok = (
        snapshot.fingerprint(worktree, cfg) == open_check["reference_untracked"]
    )
    ledger.update(
        "sensitivity_check", open_check["id"],
        restored_ok=int(restored_ok), closed_at=now(),
    )
    if not restored_ok:
        ledger.event(run["id"], cycle["id"], "restore_mismatch", json.dumps(to_restore))
        return Envelope(
            ok=False,
            error="restore is not byte-identical to the reference state",
            run={"id": run["id"], "cycle": cycle["ordinal"]},
            result={"restored": to_restore},
            next_action=NextAction(
                Verb.RESOLVE_BLOCKER,
                "The working tree does not match the pre-mutation state. Restore it by"
                " hand before continuing.",
            ),
        )
    return Envelope(
        run={"id": run["id"], "cycle": cycle["ordinal"]},
        result={"restored": to_restore, "restored_ok": True},
        next_action=NextAction(Verb.REFACTOR_OR_ADVANCE, "Restored and verified. `tdd advance`."),
    )


def cmd_target(args) -> Envelope:
    worktree, cfg, ledger, run = _context()
    cycle = ledger.open_cycle(run["id"])
    if cycle is None:
        return failure("no open cycle")
    ledger.update("cycle", cycle["id"], target_tests=json.dumps([args.test]))
    ledger.event(run["id"], cycle["id"], "target_named_by_agent", args.test)
    return Envelope(
        run={"id": run["id"], "cycle": cycle["ordinal"]},
        result={"target": args.test},
        next_action=NextAction(Verb.REFACTOR_OR_ADVANCE, "Target set. `tdd advance`."),
    )


def cmd_log_render(args) -> Envelope:
    worktree, cfg, ledger, run = _context(require_run=False)
    if run is None:
        run = ledger.one(
            "SELECT * FROM run WHERE worktree_path = ? ORDER BY id DESC LIMIT 1",
            (str(worktree),),
        )
    if run is None:
        return failure("no runs recorded for this worktree")
    text = render.friction_log(ledger, run)
    if args.out:
        Path(args.out).write_text(text)
        return Envelope(
            result={"written": args.out},
            next_action=NextAction(Verb.COMPLETE, f"Friction log written to {args.out}."),
        )
    sys.stdout.write(text)
    return Envelope(result={"rendered": True}, next_action=NextAction(Verb.COMPLETE, "Rendered."))


def cmd_metrics(args) -> Envelope:
    worktree, cfg, ledger, run = _context(require_run=False)
    return Envelope(
        result=render.metrics(ledger, str(worktree)),
        next_action=NextAction(Verb.COMPLETE, "Metrics computed."),
    )


# -- parser --------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="tdd", description=__doc__)
    sub = p.add_subparsers(dest="command", required=True)

    s = sub.add_parser("init", help="scaffold tdd.toml for review")
    s.add_argument("--force", action="store_true")
    s.set_defaults(fn=cmd_init)

    s = sub.add_parser("doctor", help="environment preflight")
    s.set_defaults(fn=cmd_doctor)

    plan = sub.add_parser("plan", help="plan contracts").add_subparsers(
        dest="plan_command", required=True
    )
    s = plan.add_parser("register")
    s.add_argument("plan")
    s.add_argument("--allow-undeclared", action="store_true")
    s.set_defaults(fn=cmd_plan_register)

    run_p = sub.add_parser("run", help="runs").add_subparsers(dest="run_command", required=True)
    s = run_p.add_parser("start")
    s.add_argument("--plan", required=True)
    s.add_argument("--executor", help="human-supplied label; agents must not use this")
    s.add_argument("--allow-dirty", action="store_true")
    s.add_argument("--allow-undeclared", action="store_true")
    s.set_defaults(fn=cmd_run_start)

    s = sub.add_parser("status")
    s.set_defaults(fn=cmd_status)

    s = sub.add_parser("advance", help="the only command that changes phase")
    s.add_argument("--retry", action="store_true", help="re-run an unchanged tree")
    s.set_defaults(fn=cmd_advance)

    cyc = sub.add_parser("cycle").add_subparsers(dest="cycle_command", required=True)
    s = cyc.add_parser("skip")
    s.add_argument("--reason", required=True)
    s.set_defaults(fn=cmd_cycle_skip)

    s = sub.add_parser("annotate")
    s.add_argument("--key", required=True)
    s.add_argument("--value", required=True)
    s.set_defaults(fn=cmd_annotate)

    s = sub.add_parser("blocker")
    s.add_argument("--kind", required=True)
    s.add_argument("--detail", required=True)
    s.set_defaults(fn=cmd_blocker)

    s = sub.add_parser("resume")
    s.add_argument("--unblock", action="store_true")
    s.add_argument("--note")
    s.set_defaults(fn=cmd_resume)

    s = sub.add_parser("sensitivity")
    s.add_argument("step", choices=["begin", "check", "end"])
    s.set_defaults(fn=cmd_sensitivity)

    s = sub.add_parser("target", help="name the target test when several new tests appeared")
    s.add_argument("test")
    s.set_defaults(fn=cmd_target)

    log = sub.add_parser("log").add_subparsers(dest="log_command", required=True)
    s = log.add_parser("render")
    s.add_argument("--out")
    s.set_defaults(fn=cmd_log_render)

    s = sub.add_parser("metrics")
    s.set_defaults(fn=cmd_metrics)
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        envelope = args.fn(args)
    except (config_mod.ConfigError, gitutil.GitError) as exc:
        envelope = failure(str(exc))
    except SystemExit as exc:
        return int(exc.code or 0)
    return envelope.emit()


if __name__ == "__main__":
    raise SystemExit(main())
